### ISSUE TITLE
Font needs to be smaller in various places in mobile view

### ISSUE THREAD

**Issue by CodeforAbj** [CodeforAbj/Music-Player#2]
- Super hits can go from 2*2 to 1*4 , also alignment in favorites 1*4 the option button goes haywire
- Check Popular artists flex its not good looking
- Alignment of Latest English and hindi section 
- Premium plans section font needs to shrink
- Queue in mobile needs wider

**Comment by CodeforAbj** [comment]
Almost done just need to reduce margin left in tab view

**Comment by CodeforAbj** [comment]
Also add Transition to favourites page

**Comment by DimitraPetrakou** [comment]
hey are these issues solved alrerady? Do you need anything else? I would like to help :)

**Comment by CodeforAbj** [comment]
No help needed thanks
